### ISSUE TITLE
docker save fails with "no space left on device"  when there is enough left

### ISSUE THREAD

**Issue by marc-hb** [ScribeMD/docker-cache#304]
https://github.com/thesofproject/sof/actions/runs/3851840976/jobs/6563431229

```
df -h ~
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   66G   18G  79% /

docker save --output ~/.docker-images.tar ghcr.io/zephyrproject-rtos/ci:latest
Error: Error: Command failed: docker save --output ~/.docker-images.tar ghcr.io/zephyrproject-rtos/ci:latest
write /home/runner/.docker_temp_4292464103: no space left on device
```

When I run the command locally `~/.docker-images.tar` is 12G. `docker images` shows it at 11.7G.

Any clue?

**Comment by Kurt-von-Laven** [comment]
Are you self-hosting? If not, I wouldn't necessarily assume that `df -h ~` displays the amount of hard drive space available to the current user of a shared cloud computing resource. There may be a policy limiting disk usage. GitHub Actions only caches up to 10 GB total. You would have to bring the image size down considerably to benefit from this action since even if it fits, it will still compete with everything else you may cache or desire to cache in the future. You are already hosting the image on GHCR though, which is ideal, and further caching would only worsen performance, regardless of image size.

**Comment by marc-hb** [comment]
If it's just too big then I'm giving up, thanks for saving me more time trying.

FYI I could not notice any visible speed up when I switched from hub.docker.com to the ghcr.io mirror! Well at least we shouldn't hit any quota with the latter...

**Comment by Kurt-von-Laven** [comment]
Sure thing; sorry this action wasn't able to help you speed up your pipeline.

Thank you for updating me. My impression that pulling from GHCR was as fast as downloading from the cache may be outdated then, but it was based on a blog post in which Thai Pangsakulyanont [reported improved performance building and pushing to GHCR](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei). Since docker-cache (which implements approach 📦 from the blog post) also has to create the tarball and upload it on cache miss and load the tarball on cache hit, Pangsakulyanont reported that it was slower than simply pulling from GHCR in 2020, but it sounds like that may no longer be the case.

**Comment by marc-hb** [comment]
In my experience a `docker pull` of this 12G image has been consistently taking ~3min from either hub.docker.com or ghcr.io. The latter maybe slightly faster but not by much. To be honest this looks like pretty decent performance considering the "zero YAML" required.

The small gap is probably because Github seems to have some private deal with Docker:
https://github.com/actions/runner-images/issues/1445#issuecomment-713861495

For an image that big the best solution is most likely to stop using Github's free runners and switch to something more persistent. In other words: to "cache" the whole runner system, not its massive content.

**Comment by Kurt-von-Laven** [comment]
Yeah, 500+ Mbps seems pretty solid. When performance work was done on [MegaLinter](https://github.com/oxsecurity/megalinter), it turned out to be surprisingly easy to significantly reduce the size of our Docker images using some standard best practices found by Googling. If you haven't already optimized the images themselves, that is where I would start personally since it's likely both less work than switching systems and valuable even if you still ultimately have to.

**Comment by marc-hb** [comment]
That image (which I don't maintain) contains a Linux system + a giant, ~5G toolchain tarball for many architectures. I doubt it could be made much smaller. Thanks for all the advice though, much appreciated.

**Comment by marc-hb** [comment]
> Well at least we shouldn't hit any quota with the [ghcr] latter...

As a coincidence someone just reported in 1445 hitting docker hub rate limits again.

**Comment by Kurt-von-Laven** [comment]
Bummer. Sorry, which repo is issue 1445 on?

**Comment by marc-hb** [comment]
5 comments above (trying not to "spam" it)

**Comment by marc-hb** [comment]
Note to "self": try a smaller docker image like this one: https://github.com/beriberikix/zephyr-docker

**Comment by Kurt-von-Laven** [comment]
One of the other MegaLinter maintainers just taught me about [dive](https://github.com/wagoodman/dive) and is finding significant opportunities to reduce our image sizes with it. It may be worth running it on Docker images you are considering to see how space efficient (or not) they are and/or using it to recommend concrete, quantified optimizations to the maintainers.
