### ISSUE TITLE
Stage "Post Cache Docker images" fails for all runners except one when missing cache

### ISSUE THREAD

**Issue by pjonsson** [ScribeMD/docker-cache#44]
I added the step from the Usage section of `README.md` before the first use of Docker (https://github.com/contiki-ng/contiki-ng/pull/1946). The second run that hits the cache works, but all runners except one fails the first run when they don't get a cache-hit. The runners fail in the "Post Cache Docker images" stage with a message similar to:

```
Post job cleanup.
docker image list --format "{{ .Repository }}:{{ .Tag }}" | 2>&1 xargs --delimiter="
" --no-run-if-empty --verbose --exit docker save --output ~/.docker-images.tar
docker save --output /home/runner/.docker-images.tar contiker/contiki-ng:63f7e91e3 node:14 node:16 buildpack-deps:stretch buildpack-deps:buster buildpack-deps:bullseye debian:9 debian:10 debian:11 node:14-alpine moby/buildkit:latest ubuntu:20.04 ubuntu:18.04 node:16-alpine node:12 node:12-alpine alpine:3.12 alpine:3.13 alpine:3.14 ubuntu:16.04

/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/contiki-ng/contiki-ng --files-from manifest.txt
file:///home/runner/work/_actions/ScribeMD/docker-cache/0.1.4/dist/post/index.js:1
eateRequire as e}from"module";var t={1312:(e,t,a)=>{Object.defineProperty(t,"__esModule",{value:true});function _interopDefault(e){return e&&typeof e==="object"&&"default"in e?e["default"]:e}var i=_interopDefault(a(2781));var n=_interopDefault(a(3685));var o=_interopDefault(a(7310));var r=_interopDefault(a(3621));var s=_interopDefault(a(5687));var p=_interopDefault(a(9796));const l=i.Readable;const d=Symbol("buffer");const c=Symbol("type");class Blob{constructor(){this[c]="";const e=arguments[0];const t=arguments[1];const a=[];let i=0;if(e){const t=e;const n=Number(t.length);for(let e=0;e<n;e++){const n=t[e];let o;if(n instanceof Buffer){o=n}else if(ArrayBuffer.isView(n)){o=Buffer.from(n.buffer,n.byteOffset,n.byteLength)}else if(n instanceof ArrayBuffer){o=Buffer.from(n)}else if(n instanceof Blob){o=n[d]}else{o=Buffer.from(typeof n==="string"?n:String(n))}i+=o.length;a.push(o)}}this[d]=Buffer.concat(a);let n=t&&t.type!==undefined&&String(t.type).toLowerCase();if(n&&!/[^\u0020-\u007E]/.test(n)){this[c]=n}}get size(){return this[d].length}get type(){return this[c]}text(){return Promise.resolve(this[d].toString())}arrayBuffer(){const e=this[d];const ...
```

**Comment by Kurt-von-Laven** [comment]
I presume the one runner that succeeded won the race to write the cache. GitHub Actions only permits a given cache key to be saved once; subsequent save attempts of the same key result in failures. Since you are running many jobs in parallel, they have all passed the cache restore step by the time the first saves the cache. Consider running a job first in series to prime the cache and waiting to start the other jobs until the first job succeeds.

On a side note, caching ~3 GB (compressed) of Docker images seems likely to be very slow as it will likely result in frequent cache evictions since GitHub Actions currently has a cache limit of 10 GB.

**Comment by pjonsson** [comment]
I'm trying to reduce a 70-80 second long docker pull that we have currently so I'm a bit hesitant to add a 10+ minute serial job to prime the cache before starting the CI tests.

The documentation for the action is quite short, is there some configuration I can set so only a specific runner from the job matrix will update the cache?

I think the usage pattern of the cache will be fine with respect to evictions, it's almost exclusively the latest image that is used. I don't have all those other images on my computer and the image works fine there, so what I really would like is to only cache a single named image. Is there a configuration key for the action to specify the name of the image one wants cached?

**Comment by Kurt-von-Laven** [comment]
That is a very good point. Evidently support for parallel runs is a longstanding feature request of the underlying official GitHub cache action that several different pull requests have been opened to address (and none yet merged). That being said, I believe it should suffice to use [`if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) in this case?

`docker image list` accepts a pattern to filter the images by, but there are typically security considerations regarding ferrying user input through to the shell:

> **Never pass unsanitized user input to this function. Any input containing shell metacharacters may be used to trigger arbitrary command execution.**

~ [Node.js v16 documentation for child_process.exec()](https://nodejs.org/docs/latest-v16.x/api/child_process.html#child_processexeccommand-options-callback)

I would accept a pull request that adds the ability to only cache a single image (or possibly a pattern) if it can be done securely though. My first instinct would be to get all of the images from Docker and filter them in TypeScript so that the user input is never passed to the shell at all, but I could certainly believe there is a better solution.

**Comment by pjonsson** [comment]
I saw the open pull requests to the cache action and they seem to be quite straightforward so I find the situation puzzling, for the first years the cache action seem to have been understaffed so they couldn't find time to review the pull requests, and after that they increased the cache size so they decided read-only cache is not an important feature.

I'm not claiming you are wrong, but your attempts to help are cryptic for someone who doesn't speak CI fluently, can you spell out the complete if to run the action on every runner, but make the post-action conditional on the job-id of the runner?

I'm not sure I understand your concern for injection attacks since the user that controls the CI can add an action that runs arbitrary commands, but even so, docker save sanity checks the input:
```
> docker save --output /tmp/file nonexistent
Error response from daemon: No such image: nonexistent
```

I'm sure actions don't work this way, but here's a sketch of the functionality I would like:

```
const saveDockerImages = async (): Promise<void> => {
  const key = getInput("key", { required: true });
  if (getState(CACHE_HIT) === "true") {
    info(`Cache hit occurred on the primary key ${key}, not saving cache.`);
  } else if (env.SAVE_DOCKER_IMAGE != "" && !env.SAVE_DOCKER_IMAGE) {
    info(`Runner excluded from saving cache.');
  } else {
    const images = getInput("docker-images");
    if (images === "") {
      await execBashCommand(
        'docker image list --format "{{ .Repository }}:{{ .Tag }}" | ' +
          '2>&1 xargs --delimiter="\n" ' + '--no-run-if-empty --verbose --exit ' +
          `docker save --output ${DOCKER_IMAGES_PATH}`
      );
    } else {
      await execBashCommand(
           `docker save --output ${DOCKER_IMAGES_PATH} ` + images
      );
    }
    await saveCache([DOCKER_IMAGES_PATH], key);
  }
};
```

**Comment by Kurt-von-Laven** [comment]
My impression was that they have been struggling to choose between a number of subtly different competing proposals that have been superseding each other in a game of continuous leap frog, but I haven't dug too deep.

Apologies; I underestimated how tricky it would be to handle caching with parallel jobs. This isn't a perfect solution since it is impossible to guarantee perfect synchrony between the correlated caches and the Docker caches, but the jobs can be re-run if needed. In most cases, `<key remainder>` will take the form `{{ hashFiles(...) }}`.

```yaml
- name: Get operating system name and version.
  id: os
  run: echo "::set-output name=image::$ImageOS"
  shell: bash // Required on Windows runners and in composite actions; optional otherwise.
- name: Cache the fact that Docker images are cached.
  id: docker-correlated-cache
  uses: actions/cache@v3.0.4
  with:
    path: ~/.dockerImagesCached
    key: docker-correlate-{{ steps.os.outputs.image }}-{{ github.job }}-<key remainder>
- name: Cache Docker images.
  if: steps.docker-correlated-cache.outputs.cache-hit == 'true' || github.job == <id of the one job that saves the cache>
  uses: ScribeMD/docker-cache@0.1.4
  with:
    key: docker-{{ steps.os.outputs.image }}-<key remainder>
- name: Denote that Docker images are being cached.
  if: steps.docker-correlated-cache.outputs.cache-hit != 'true' // Optional since touch succeeds if the file already exists.
  run: touch ~/.dockerImagesCached
  shell: bash // Required on Windows runners and in composite actions; optional otherwise.
```

A more robust solution would be to include `{{ github.job }}` in the Docker cache key, but that won't work in your case since 3 GB * 17 parallel jobs = 51 GB > 10 GB cache size limit. You may alternatively be able to use actions/upload-artifact and actions/download-artifact or [job outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) to coordinate between jobs. It feels like there may be some fundamental inefficiency in your workflow that is more rewarding to address here though since, if I understand correctly, you currently build the same Docker image 17 times. Maybe it would be preferable to have a single job dedicated to building the Docker image that only runs when the image isn't already in Docker Hub, and the matrix of parallel jobs can then always safely pull the correct image. Also, you will get better performance than docker-cache can ever possibly provide simply by using the [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) since that will spare you both the `docker load` and `docker save` steps (to say nothing of pushing and pulling 1 image rather than 20 in your case). This doesn't preclude pushing to Docker Hub if needed. docker-cache is intended for those who don't control where their Docker image is homed (generally meaning they are pulling from some place other than the GitHub Container Registry but neither building nor pushing). [The official Docker build push action](https://github.com/docker/build-push-action) is better suited to building and pushing Docker images as it uses Docker layer caching. [CircleCI's documentation](https://circleci.com/docs/2.0/docker-layer-caching) explains Docker layer caching well in case that is helpful.

My concern regarding injection attacks is that it may be more difficult for some code reviewers to notice a cleverly crafted injection attack than someone blatantly proposing the addition of malicious steps to a CI workflow. I'm afraid `docker save` and indeed any other Bash command are powerless to sanitize arbitrary Bash input since an injection attack can inject entirely new Bash commands that aren't parsed as arguments to existing commands. Happy to accept a PR that does the filtering securely on the TypeScript side though.

**Comment by pjonsson** [comment]
It would be good to have your example for multiple runners in the documentation, because a job matrix is quite prominent in the Github documentation and I doubt that someone who isn't an expert at Github workflows will figure out that they need several additional steps to avoid failure.

I think it's already been a couple of weeks, but I did the math on how frequently the docker images are updated in the past 15 months, and the number was just under 5.5% of the commits. That number is certainly lower now, so if the commits that update the docker image take 24 hours to get through the CI, and the other commits take 24 seconds, the balance is fair.

As I wrote in #45, I don't know where the 3 Gb of images come from, they don't appear on my local Ubuntu 20.04/22.04 installations when I build/pull the docker image we are interested in and they are not used by the CI unless Github does something hidden behind the scenes. Even if docker is exceptionally smart and somehow manages to utilize some local Github cache to save bandwidth on downloads, I don't see how the Alpine Linux image would enter the picture since it is based on musl, so all dynamically linked binaries in the system will be different from the Ubuntu-based docker image that is used by the CI. And even if I'm wrong about how smart docker is and it manages to get a partial binary from the alpine image and then download the ELF headers for those binaries from elsewhere, why does it need 3 alpine images (3.12, 3.13, and 3.14)? There are also 3 debian images (9, 10, 11), and those seem like a much closer match to the Ubuntu 18/20-based image the CI uses. An even closer match to the Ubuntu 18/20-based image the CI uses are the ubuntu 18/20 images, and I get one of them on my local machine when I build a new image.

**Comment by Kurt-von-Laven** [comment]
At some point in the last week or so the GitHub Actions cache service stopped treating attempting to save a cache with a pre-existing key as an error, so hopefully that addresses one of your issues. The official cache client still logs a warning in this case, so the pull request linked above isn't moot for those desiring log tidiness.

>94.5% is quite a good cache hit rate!

I also have no idea where the additional images come from. We haven't been seeing those extra images when pulling from Docker Hub, but when we build an empty image from scratch or pull a small test image from GitHub Container Registry, we measure an extra 1358 MB of images, namely: `node:14 node:16 buildpack-deps:buster buildpack-deps:bullseye debian:10 debian:11 node:14-alpine node:16-alpine buildpack-deps:stretch debian:9 ubuntu:20.04 ubuntu:18.04 moby/buildkit:latest node:12 node:12-alpine alpine:3.12 alpine:3.13 alpine:3.14 ubuntu:16.04`. I also suspect GitHub may be doing something under the hood. I know the GitHub Actions team is hard at work on Docker-related matters since [rootless-docker](https://github.com/ScribeMD/rootless-docker) broke several times in a row. It sounds like that filtering feature you proposed may become a must have rather than an optional thing.

**Comment by Kurt-von-Laven** [comment]
The list of extra images is identical to [the list of cached Docker images on Ubuntu-20.04](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#cached-docker-images), which is the runner we are using. I don't understand why the images are present some times but not others.

**Comment by pjonsson** [comment]
If the upstream changes converts the previous failure with multiple runners into a warning, I'm happy to keep things simple and live with the warning. It would be helpful with README.md mentioning that the warning is expected with multiple runners building the same image, and that the warning can be ignored in that case.

With respect to performance, I wasn't aware how slow `docker save/load` is on the Github CI machines (it's fast on my local SSD, but that apparently frequently writes 500+ Mb/s), so the docker image used by the CI might be too big for the cache to be beneficial.

If the list of additional images is documented by Github, that can be hardcoded into the action and the concern for injection attacks disappears. The set of images is apparently different for Ubuntu 22.04:

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#cached-docker-images

**Comment by Kurt-von-Laven** [comment]
For better or worse #81 was nearly complete at the time I discovered the upstream fix, so we might as well follow through and land it for the sake of those desiring log tidiness at this point. Hopefully that also obviates the need to document the warning?

Here is an example of the warning from the "Post Cache Docker images" step of [one of our workflow runs](https://github.com/ScribeMD/docker-cache/runs/7421881643?check_suite_focus=true):

> Failed to save: Unable to reserve cache with key docker-ubuntu20-5e491f28955b811ef9c159654e1c6855679b96b9c51b965a53e1aef730e122bd, another job may be creating this cache. More details: Cache already exists. Scope: refs/heads/main, Key: docker-ubuntu20-5e491f28955b811ef9c159654e1c6855679b96b9c51b965a53e1aef730e122bd, Version: b2b642126ebc35902bc8d69360ecc5394e03fb014b491c77dfdf140754af783d

Indeed saving and loading Docker images is slow. Thai Pangsakulyanont investigates Docker performance in [this helpful blog post](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei), which is where my recommendation to use GitHub Container Registry instead comes from if that is an option for you.

I don't recommend hard-coding the list of cached Docker images since as you point out the list differs from OS image to OS image. Furthermore, the list changes over time within each image, and it would be quite challenging to atomically roll out an update to the list alongside an update to the underlying OS image, resulting in potentially long-lasting cache pollution. I agree with you that we can solve this problem without the need for an additional input. My instinct is rather to subtract the images that are already present in the main step from the list of images present in the post step and of course to document that any images pulled before docker-cache is run will not be cached. Please let me know if you foresee any issues with this approach. If not, I am confident we can ship it along with the new `read-only` input within a week.

**Comment by pjonsson** [comment]
I think the solution with a diff between before/after that you suggest is a good idea, it should be stable across different runners and Github configurations. The only issue I see is that projects that use some base image that Github does not provide will get the base image and the built image in their cache, but this is still a vast improvement over the current additional images, which are 1+ Gb if I understand you correctly.

**Comment by Kurt-von-Laven** [comment]
I see your point. That is a good argument for adding the filtering feature you proposed eventually. We will most likely wait until someone has a concrete need for it to prioritize it since some people may actually prefer caching the base image. Yes, it is over 1 GB of cache space that is being wasted on the GitHub-hosted Ubuntu 20.04 runner currently. I still have no idea why we don't always encounter this overhead.

**Comment by pjonsson** [comment]
Oh, if pulling before calling docker-cache gets around the need for configurable filtering for those who do not wish to cache their base image, I think everything is fine. I wouldn't have figured out that I should pull the base image before docker-cache without you mentioning it though, so it's probably worth to mention that in README.md.

**Comment by Kurt-von-Laven** [comment]
Sweet. That is definitely something that we will document once it becomes a feature. I agree that nobody could reasonably be expected to intuit such a behavior.

**Comment by Kurt-von-Laven** [comment]
> I still have no idea why we don't always encounter this overhead.

The answer finally hit me. When [rootless-docker](https://github.com/ScribeMD/rootless-docker) is used, the pre-cached Docker images aren't accessible. By default, rootful Docker is used, in which case the pre-cached Docker images _are_ accessible. We only recently introduced a scenario in which we exercise docker-cache without rootless-docker, which is why we started noticing the bloated caches on our end.
