### ISSUE TITLE
Caching Megalinter ?

### ISSUE THREAD

**Issue by NunesMig** [ScribeMD/docker-cache#614]
Hello! 

Basically I'm pulling oxsecurity/megalinter/flavors/terraform@7.3.0 to run megalinter on pull requests. This is something I'd like to avoid doing repeatedly as I am now and would like to cache the the pulled image. 

When I used your action it seemed to recognize the image but in the "Post Cache Docker Images" it said that it had "No docker images to save". 

Could you help me with this bit or even tell me if what I am trying to do is possible using your action?

Thank you for your time!

**Comment by Kurt-von-Laven** [comment]
What you are trying to do is possible to do with docker-cache. We use this action to cache various flavors of MegaLinter ourselves. The action automatically filters out any Docker images present before it is run, so my first instinct would be to move the step earlier in your workflow as described in the README. Please let us know if that isn't the solution in your case.

**Comment by NunesMig** [comment]
The order I have laid out in my workflow basically follows this logic:
- Set up job
- Pull oxsecurity/megalinter/terraform:v7.3.0
- Cache Docker Images
- Checkout the Code
- Run Megalinter

I feel like it is in the correct place in the workflow, but as of today I still haven't managed to make it work. 
If you have any suggestions I'd appreciate them. 

Thank you very much for your time!

**Comment by Kurt-von-Laven** [comment]
To reiterate, you need to swap steps two and three. Note the following excerpt of the README:

> Filter out Docker images that are present before the action is run

**Comment by NunesMig** [comment]
I did notice it at first but I've been running into the same issue which is:

As I am running the "Run Megalinter" step, which is currently sort of as follows:

`- name: megalinter` 
  `uses: oxsecurity/megalinter/flavors/terraform@v7.3.0` 

I believe this triggers the `Pull` of the image to always come after the `Set up job` and before the `cache` step

Do you know of another way for me to try and do this? 
Or could you exemplify or show me how you go about it yourself as you've said previously that you also use the action to cache various megalinter flavors?

I apologize for the request in advance but I'm quite new to GitHub so all of this is pretty new to me 😅

Thank you for your time once again!

**Comment by Kurt-von-Laven** [comment]
I would guess from the snippet you pasted that the problem is that you are pulling the Docker image in a pre-step, meaning it happens before any main steps are run. docker-cache checks for pre-existing images in its main step, so this would cause the MegaLinter Docker image to be filtered out. docker-cache logs the images it finds during both its main and post steps, so you can verify whether MegaLinter is listed in both, meaning it was filtered out. mega-linter-runner automatically pulls the appropriate Docker image if it isn't present, so there's no need to pull it manually. We run MegaLinter as a pre-commit hook, so I am not sure how helpful [our approach](https://github.com/ScribeMD/docker-cache/blob/main/.github/workflows/test.yaml) will be to you unless you also wish to run MegaLinter locally.

**Comment by Kurt-von-Laven** [comment]
I'm going to assume that solved your problem, but please let me know if it didn't.
